### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by omidfi** [omidfi/moro#1]
- [x] add a nice about page, support an NGO
- [ ] add chilicorn ascii as sponsor
- [ ] show a random cow [link](https://github.com/sindresorhus/cows/blob/master/cows.txt)
- [x] 1. ask for code review
- [x] 1. add .npmrc
   Is this still needed with yarn? Or it will use exact versions anyhow
- [x] 1. refactor helpers out of the main file
- [x] 1. add feature to be able to add notes, which get saved with time stamp 
 - [x]  document the above feature 
- [x] 1. make work day length configurable
- [x] 1. add gif/screen recording
- [x] 1. remove comments out of readme
- [x] add standard linter to test
- [x] use npm link for local development
- [x] > currently the only way to set breaks is $: moro -break 45  which sets the total amound of break. But would be helpful for you to have a note taking feature something like $: moro note "I had a 3 hour break"  which saves the time stamp as well?

**Comment by luQx** [comment]
Would be cool to see calculated +/- hours in the `moro report --all` list.

**Comment by omidfi** [comment]
@luQx thanks for commenting. 

Do you mean for each single day? Because that's already shown, with no sign when it is positive, and with negative sign when you have worked less than a full day

**Comment by luQx** [comment]
Hey, I mean like calculated overall. Maybe just show it in a separate row on the bottom of the table.

**Comment by mario-s** [comment]
@luQx I'm trying to add a row that shows the sum. This row will be added when a week is over (depending on the week number). Could that also fit your needs?

**Comment by luQx** [comment]
@mario-s Yeah, sure.

**Comment by omidfi** [comment]
@luQx current version has sum fo hours per week, you can update and try it, thanks to @mario-s :)
